//
//  ViewController2.swift
//  SceneDetector
//
//  Created by Kate Rupar on 2/10/18.
//  Copyright © 2018 Ray Wenderlich. All rights reserved.
//

import UIKit

class ViewController2: UIViewController {
  let cameraController = CameraController()
  
  @IBOutlet fileprivate var captureButton: UIButton!
  
  ///Displays a preview of the video output generated by the device's cameras.
  @IBOutlet fileprivate var capturePreviewView: UIView!
  
  ///Allows the user to put the camera in photo mode.
  @IBOutlet fileprivate var photoModeButton: UIButton!
  @IBOutlet fileprivate var toggleCameraButton: UIButton!
  @IBOutlet fileprivate var toggleFlashButton: UIButton!
  
  ///Allows the user to put the camera in video mode.
  @IBOutlet fileprivate var videoModeButton: UIButton!
  
  override var prefersStatusBarHidden: Bool { return true }
}

extension ViewController2 {
  override func viewDidLoad() {
    func configureCameraController() {
      cameraController.prepare {(error) in
        if let error = error {
          print(error)
        }
        
        try? self.cameraController.displayPreview(on: self.capturePreviewView)
      }
    }
    
    func styleCaptureButton() {
      captureButton.layer.borderColor = UIColor.black.cgColor
      captureButton.layer.borderWidth = 2
      
      captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
    }
    
    styleCaptureButton()
    configureCameraController()
  }
}

